### ISSUE TITLE
RuntimeError: "cryptography requires setuptools 18.5 or newer, please upgrade to a newer version of setuptools" while running setup.py during controller vm provisioning.

### ISSUE THREAD

**Issue by teterkin** [lekum/introduction-to-ansible#2]
```
    controller:   Running setup.py (path:/tmp/pip_build_root/ansible/setup.py) egg_info for package ansible
    controller:
    controller:     no previously-included directories found matching 'hacking'
    controller: Downloading/unpacking jinja2 (from ansible)
    controller: Requirement already satisfied (use --upgrade to upgrade): PyYAML in /usr/lib/python2.7/dist-packages (from ansible)
    controller: Downloading/unpacking paramiko (from ansible)
    controller: Downloading/unpacking cryptography (from ansible)
    controller:   Running setup.py (path:/tmp/pip_build_root/cryptography/setup.py) egg_info for package cryptography
    controller:     Traceback (most recent call last):
    controller:       File "<string>", line 17, in <module>
    controller:       File "/tmp/pip_build_root/cryptography/setup.py", line 28, in <module>
    controller:         "cryptography requires setuptools 18.5 or newer, please upgrade to a "
    controller:     RuntimeError: cryptography requires setuptools 18.5 or newer, please upgrade to a newer version of setuptools
    controller:     Complete output from command python setup.py egg_info:
    controller:     Traceback (most recent call last):
    controller:
    controller:   File "<string>", line 17, in <module>
    controller:
    controller:   File "/tmp/pip_build_root/cryptography/setup.py", line 28, in <module>
    controller:
    controller:     "cryptography requires setuptools 18.5 or newer, please upgrade to a "
    controller:
    controller: RuntimeError: cryptography requires setuptools 18.5 or newer, please upgrade to a newer version of setuptools
    controller:
    controller: ----------------------------------------
```
To fix this I did the following:
`vagrant@controller:~$ sudo pip install setuptools --upgrade`
But still I have a problem to build Ansible ( I have openned a separate issue: https://github.com/lekum/introduction-to-ansible/issues/1).
Why don't you use official Ansible installation method on Ubuntu?
Like this:
```
$ sudo apt-get update && sudo apt-get install software-properties-common
$ sudo apt-add-repository ppa:ansible/ansible
$ sudo apt-get update && sudo apt-get install ansible
```

**Comment by lekum** [comment]
Hi @teterkin !

Thanks for spotting the problem. This repo was for a workshop 3 years ago, and I'm sure many things have changed in Ansible (even in Ubuntu, this probably should be changed to support 18.04).

If you prepare a Pull Request with the changes, I will accept them :wink:

**Comment by teterkin** [comment]
Thank you! Let's see If I can make it. ;)
